// AUTOGENERATED by packages/release (bun run release:cli) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored dist outputs): this pins the
// published CLI release that the cloud's /api/cli/binary route redirects to.
// Re-run the release pipeline, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release run fills in the tag + checksums.

import type { TCliRelease } from "./release-types";

export const CLI_RELEASE: TCliRelease = {
  repo: "openllmsh/cli",
  tag: "v2.0.0-alpha.3",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "ba7210676a37d4fff5ae12bfa7da3a739e5b1409a08f9b6375b9b581352560f5",
    "darwin-x64-baseline":
      "16f5c9fa443dc3df9cd8e726fa33237362f7106fd5f76728d51edb9d4e887520",
    "linux-x64-baseline":
      "e580f9190f5eeabe4cc4508966984eb04d4c8e76087ce1f56496b47d0bd45e5a",
    "linux-arm64":
      "2b9c4ad64c726aa3c17de3e49942b56f5084c9b2430ab283e85f228c0f91d5ac",
  },
};
