// AUTOGENERATED by packages/release (bun run release:cli) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored dist outputs): this pins the
// published CLI release that the cloud's /api/cli/binary route redirects to.
// Re-run the release pipeline, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release run fills in the tag + checksums.

import type { TCliRelease } from "./release-types";

export const CLI_RELEASE: TCliRelease = {
  repo: "openllmsh/cli",
  tag: "v2.1.5-alpha.1",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "d8f6ba5b8d70484390639e608018697e3eb429289f6bdd46236cd5cb6b2d0ca9",
    "darwin-x64-baseline":
      "7ef389941024cb6a1187a9abc58d5fe489a54ab1e5c5d1a516f5aafd61a0cf96",
    "linux-x64-baseline":
      "ac8701f4ffc88e8f60171d643e23f833e3f5920721be389784c685f192941fba",
    "linux-arm64":
      "ee101b6b3ab6c596bf042274c2b6e926ea7949376c82c17f48a03b2f728b3157",
  },
};
