// AUTOGENERATED by packages/release (bun run release:cli) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored dist outputs): this pins the
// published CLI release that the cloud's /api/cli/binary route redirects to.
// Re-run the release pipeline, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release run fills in the tag + checksums.

import type { TCliRelease } from "./release-types";

export const CLI_RELEASE: TCliRelease = {
  repo: "openllmsh/cli",
  tag: "v2.1.10",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "d4373cb738ce083eec6a16911c3af21b30855c02c7d5c738f487e8553734a777",
    "darwin-x64-baseline":
      "62917e9e794077e7bf3ec07af480d8a6f80ca115821b6b8989d3fca3f4424739",
    "linux-x64-baseline":
      "48518d2edcf34e99a0a92f7e487897c659b6fb1ee958a1ad2f60b1c24cd5898d",
    "linux-arm64":
      "4e48cbbdd31f1159a909dd438471976a214588ecc2aa201fa8847aafc426173e",
  },
};
