#!/usr/bin/env bun

/**
 * Generate the CLI's committed SDK artifacts from the Effect `HttpApi`
 * (`@openllm/schema/http-api`) — MONOREPO-ONLY (the `openllmc` mirror ships
 * the committed outputs, never this generator's inputs).
 *
 * Two artifacts land in `src/sdk/generated/` (both COMMITTED):
 *
 *   - `openapi.json` — `OpenApi.fromApi(Api)` run through the SAME sanitize
 *     the served `/api/swagger` doc uses (admin paths stripped, `/api`
 *     server, v1-first ordering), so the SDK surface can never drift from
 *     the published spec.
 *   - `operations.ts` — a typed, dependency-free operations table derived
 *     from the spec: one entry per OpenAPI operation (method, path,
 *     path/query params, request-body presence, summary). The MCP layer
 *     derives its native-API tools from this table, so tool coverage tracks
 *     the spec automatically — no hand-picked subset.
 *
 * A drift test (`tests/cli/sdk-drift.test.ts`) regenerates in-memory and
 * fails when the committed artifacts are stale — same spirit as the
 * daemon-binary-sources parity test.
 */

import * as fs from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildSanitizedSpec } from "../../api/handlers/swagger";

const PKG_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(PKG_ROOT, "src", "sdk", "generated");

// runtime-only: the OpenAPI 3 subset we walk.
type TSpecOperation = {
  operationId?: string;
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: Array<{
    name: string;
    in: "path" | "query" | "header" | "cookie";
    required?: boolean;
    description?: string;
    schema?: unknown;
  }>;
  requestBody?: {
    content?: Record<string, { schema?: unknown }>;
    required?: boolean;
  };
};
type TSpecDoc = {
  paths?: Record<string, Record<string, TSpecOperation>>;
};

const METHODS = ["get", "post", "put", "patch", "delete"] as const;

/** One generated operation row — the runtime shape `operations.ts` exports. */
export type TGeneratedOp = {
  readonly id: string;
  readonly method: (typeof METHODS)[number];
  readonly path: string;
  readonly summary: string;
  readonly tags: readonly string[];
  readonly pathParams: readonly string[];
  readonly queryParams: readonly {
    readonly name: string;
    readonly required: boolean;
  }[];
  readonly hasBody: boolean;
};

export const generateOperations = (spec: TSpecDoc): TGeneratedOp[] => {
  const ops: TGeneratedOp[] = [];
  for (const [path, byMethod] of Object.entries(spec.paths ?? {})) {
    for (const method of METHODS) {
      const op = byMethod[method];
      if (op === undefined) continue;
      const params = op.parameters ?? [];
      const id =
        op.operationId ??
        `${method}_${path.replace(/[{}]/g, "").replace(/[^a-zA-Z0-9]+/g, "_")}`;
      ops.push({
        id,
        method,
        path,
        summary: op.summary ?? op.description ?? "",
        tags: op.tags ?? [],
        pathParams: params.filter((p) => p.in === "path").map((p) => p.name),
        queryParams: params
          .filter((p) => p.in === "query")
          .map((p) => ({ name: p.name, required: p.required === true })),
        hasBody: op.requestBody !== undefined,
      });
    }
  }
  // Deterministic output: sort by path then method so regeneration is
  // reproducible (the drift test depends on byte-stable output).
  ops.sort((a, b) =>
    a.path === b.path
      ? a.method.localeCompare(b.method)
      : a.path.localeCompare(b.path),
  );
  return ops;
};

export const operationsSource = (ops: readonly TGeneratedOp[]): string =>
  `// AUTOGENERATED by packages/cli/scripts/generate-sdk.ts — DO NOT EDIT BY HAND.
// COMMITTED on purpose: the openllmc mirror ships these artifacts without the
// monorepo generator (which needs @openllm/schema). Regenerate with
// \`bun run --cwd packages/cli generate:sdk\` and commit the diff; the drift
// test (tests/cli/sdk-drift.test.ts) fails when this file is stale.

export type TApiOperation = {
  readonly id: string;
  readonly method: "get" | "post" | "put" | "patch" | "delete";
  readonly path: string;
  readonly summary: string;
  readonly tags: readonly string[];
  readonly pathParams: readonly string[];
  readonly queryParams: readonly {
    readonly name: string;
    readonly required: boolean;
  }[];
  readonly hasBody: boolean;
};

export const API_OPERATIONS: readonly TApiOperation[] = ${JSON.stringify(ops, null, 2)};
`;

export const generateArtifacts = (): {
  readonly openapiJson: string;
  readonly operationsTs: string;
} => {
  const spec = JSON.parse(buildSanitizedSpec()) as TSpecDoc;
  const ops = generateOperations(spec);
  return {
    openapiJson: `${JSON.stringify(spec, null, 2)}\n`,
    operationsTs: operationsSource(ops),
  };
};

if (import.meta.main) {
  const { openapiJson, operationsTs } = generateArtifacts();
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(join(OUT_DIR, "openapi.json"), openapiJson);
  fs.writeFileSync(join(OUT_DIR, "operations.ts"), operationsTs);
  const count = (JSON.parse(openapiJson) as TSpecDoc).paths;
  console.log(
    `[generate-sdk] wrote openapi.json (${Object.keys(count ?? {}).length} paths) + operations.ts → ${OUT_DIR}`,
  );
}
